### ISSUE TITLE
template Completable is not defined

### ISSUE THREAD

**Issue by ghost** [huntlabs/hunt-http#11]
Using this `dub.sdl`:

~~~
dependency "hunt-http" version="~>0.2.2"
~~~

and this `app.d`:

~~~d
import hunt.http.client;
~~~

Gives this result:

~~~
$ dub build
Performing "debug" build using C:\dmd2\windows\bin\dmd.exe for x86_64.
hunt 1.2.2: target for configuration "library" is up to date.
hunt-http 0.2.2: building configuration "library"...
C:\Users\Steven\AppData\Local\dub\packages\hunt-http-0.2.2\hunt-http\source\
hunt\http\client\HttpClient.d(84,5): Error: template instance
`Completable!HttpClientConnection` template Completable is not defined
~~~

**Comment by Heromyth** [comment]
Can you have a try with hunt-http 0.3.0-rc.2? The HttpClient have been improved greatly since  hunt-http 0.2.x.

**Comment by ghost** [comment]
~~~
$ dub build
Performing "debug" build using C:\dmd2\windows\bin\dmd.exe for x86_64.
hunt 1.3.0-rc.4: target for configuration "library" is up to date.
hunt-net 0.3.3: target for configuration "default" is up to date.
etc ~master: building configuration "application"...
Linking...
lld-link: error: subsystem must be defined
~~~

**Comment by Heromyth** [comment]
It seems we have to do some more tests on Windows. The most safe way is to use dmd + vs 2017.

PS: There is no problem with dmd + vs 2017.

**Comment by ghost** [comment]
@Heromyth why was this closed?

**Comment by Heromyth** [comment]
> 
> 
> @Heromyth why was this closed?

It's recommended using dmd + Visual C++ tools. We have tested. There are many bugs for dmd + mingw tools.

**Comment by ghost** [comment]
@Heromyth did you see this?

https://dlang.org/changelog/2.087.0#msvcrt

**Comment by Heromyth** [comment]
> 
> 
> @Heromyth did you see this?
> 
> https://dlang.org/changelog/2.087.0#msvcrt

We are still using dmd 2.086.1 and below. It will be soon to upgrade to dmd 2.087
