### ISSUE TITLE
Serve static files

### ISSUE THREAD

**Issue by kambrium** [huntlabs/hunt-http#21]
How do I serve static files with hunt-http? Assume that I have a directory with an index.html, some other HTML files, images and a CSS file. No dynamic content. Thanks for helping!

**Comment by Heromyth** [comment]
Please check this [example](https://github.com/huntlabs/hunt-http/blob/master/examples/HttpDemo/source/server.d#L83).  Use the method `resource` to specify the location for some static files.

**Comment by kambrium** [comment]
Thanks!
